---

# Project info
site_name: ''
site_url: https://builder555.github.io/PineSAM/
site_description: "PineSAM is a Bluetooth LE app to control the Pinecil V2 through a browser."
copyright: Copyright &copy; 2023 Builder555

# repo config
repo_name: PineSAM
repo_url: https://github.com/builder555/PineSAM/
edit_uri: edit/dev/docs/
docs_dir: docs

# Theme and config
theme:
  name: material
  custom_dir: docs/overrides
  favicon: img/favicon.ico
  logo: img/PineSAM_logo-A017A5.png
  icon:
    edit: material/file-edit-outline
    repo: fontawesome/brands/github
  # Don't auto-load Google fonts- Privacy issue
  font: false
  language: en

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - bash
    - python
    - yaml
    - javascript
    - powershell

  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.top
      # tab buttons in the top banner
    - navigation.tabs  
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.path
    - navigation.footer
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.action.edit
    # adds a copy button to all codeblocks for convenience
    - content.code.copy

# For Privacy - defines/uses local fonts
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/fonts.css

extra_javascripts:
  - assets/javascripts/extra.js

# Plugins
plugins:
  - autolinks
  - search
  - git-committers:
      repository: neil-forks/PineSAM-river
      branch: NeilHanlon-patch-1
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - awesome-pages:
  - macros:
      # true if in CD/CI environment
      on_error_fail: true

# lower-right banner info
extra:
  social:
    - icon: simple/githubsponsors
      link: https://github.com/sponsors/builder555
      name: Sponsor the project
    - icon: fontawesome/regular/star
      link: https://github.com/builder555/PineSAM
      name: Give it a Star if you like!
    - icon: fontawesome/brands/github-alt
      link: https://github.com/builder555/PineSAM
      name: Go to repository


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  # built-in icons: material, fontAwesome, octicons, simple
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
      custom_checkbox: true
  - toc:
      permalink: "🔗&#xFE0E;"
      # for screenreaders
      permalink_title: Anchor link to this section for reference