site_name: PineSAM
site_url: https://builder555.github.io/PineSAM/
repo_name: PineSAM
repo_url: https://github.com/builder555/PineSAM/
site_description: "PineSAM is a Bluetooth BLE app to control the Pinecil V2 through a browser."
edit_uri: edit/dev/docs/

nav:
  - Home: index.md
  - Installation:
      - Premade Binaries: install-guide/Premade-binaries.md
      - Build from Scripts: install-guide/Dev-scripts.md
  - Operation: user-guide/Usage.md
    - Settings Categories: user-guide/Settings.md
    - Backend: user-guide/Backend.md
  -Troubleshooting: Troubleshooting.md

extra:
  social:
    - icon: simple/github
      link: https://github.com/builder555/PineSAM
      name: GitHub
    - icon: fontawesome/solid/heart
      link: https://github.com/sponsors/builder555
      name: Sponsor the project

theme: readthedocs

