---

# Project info
site_name: ''
site_url: https://builder555.github.io/PineSAM/
site_description: "PineSAM is a Bluetooth BLE app to control the Pinecil V2 through a browser."

# repo config
repo_name: PineSAM
repo_url: https://github.com/builder555/PineSAM/
edit_uri: edit/dev/docs/
docs_dir: docs

# Theme and config
theme:
  name: material
  custom_dir: docs/overrides
  logo: img/PineSAM_logo-A017A5.png
  favicon: img/favicon.ico
  font:
    code: Red Hat Text
  icon:
    edit: material/file-edit-outline
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - bash
    - python
    - yaml
    - javascript
    - powershell
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.action.edit

# Plugins
plugins:
  - autolinks
  - search
  - git-authors:
      show_contribution: true
      fallback_to_empty: true
      sort_authors_by: contribution
  - git-committers:
     repository: neil-forks/PineSAM-river
     branch: NeilHanlon-patch-1
     token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - awesome-pages:
  - git-revision-date-localized:
      type: date

# Markdown Extensions
markdown_extensions:
  # Adds ability to define abbreviations
  - abbr
  - attr_list
  # block-styled side content
  - admonition
  # Table of Contents
  - toc:
      permalink: "🔗&#xFE0E;"
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.tasklist
  - footnotes
  - def_list
  - meta
